[tool.poetry]
name = "awesome"
version = "0.1.0"
description = ""
authors = ["Aidan O'Brien"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
